### ISSUE TITLE
OSX immediate failure

### ISSUE THREAD

**Issue by ckhrysze** [boydm/scenic_driver_glfw#23]
I took the code I'm testing on Ubuntu to my Macbook, and the program brings up a window, then crashes. The window is visible but non-interactive. The window also has a pulsing black glow around the main windows. After the computer restarts, the terminal restores its session, and the stack trace is:

```
00:02:30.758 [error] GenServer :main_viewport terminating
** (stop) exited in: GenServer.call(#PID<0.5579.0>, :which_children, :infinity)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir) lib/gen_server.ex:989: GenServer.call/3
    (scenic) lib/scenic/scene.ex:1213: Scenic.Scene.do_start_child_scene/6
    (scenic) lib/scenic/view_port.ex:532: Scenic.ViewPort.handle_cast/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", {:set_root, {Test.Scene.Home, nil}, nil}}
State: %{default_scene: {Test.Scene.Home, nil}, default_scene_activation: nil, driver_registry: %{}, drivers: [], dynamic_root_pid: nil, dynamic_supervisor: #PID<0.5578.0>, hover_primitve: nil, input_captures: %{}, master_graph: %{0 => %{data: {Scenic.Primitive.Group, [1]}, transforms: %{}}, 1 => %{data: {Scenic.Primitive.SceneRef, nil}}}, master_graph_key: {:graph, #Reference<0.4259598032.1965031428.32205>, nil}, master_styles: %{}, master_transforms: %{}, max_depth: 256, on_close: :stop_system, root_config: nil, root_graph_key: nil, root_scene_pid: nil, size: {700, 600}, supervisor: #PID<0.5492.0>}
```

I then started a new application with scenic.new, and the same thing occurred when I ran scenic.run.

**Comment by boydm** [comment]
Which version of Ubuntu? Which graphics driver? Which Erlang? Which Elixir? etc... Which Mac?
Does it work on the MacBook normally? (Suspect yes...)
