### ISSUE TITLE
0.8.0 is not released on hex.pm

### ISSUE THREAD

**Issue by axelson** [boydm/scenic_driver_glfw#9]
0.8.0 that deals with the breaking changes in scenic_math is not yet released. This results in errors like:

```
06:29:39.571 [error] Task #PID<0.439.0> started from :glfw terminating
** (UndefinedFunctionError) function Scenic.Math.Vector.invert/1 is undefined (module Scenic.Math.Vector is not available)
    Scenic.Math.Vector.invert({6, 0})
    (scenic_driver_glfw) lib/glfw/compile.ex:433: Scenic.Driver.Glfw.Compile.do_compile_tx/3
    (scenic_driver_glfw) lib/glfw/compile.ex:121: Scenic.Driver.Glfw.Compile.compile_primitive/4
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    (scenic_driver_glfw) lib/glfw/compile.ex:124: Scenic.Driver.Glfw.Compile.compile_primitive/4
    (scenic_driver_glfw) lib/glfw/compile.ex:107: Scenic.Driver.Glfw.Compile.graph/3
    (scenic_driver_glfw) lib/glfw/graph.ex:370: Scenic.Driver.Glfw.Graph.render_one_graph/3
    (elixir) lib/enum.ex:765: Enum."-each/2-lists^foreach/1-0-"/2
Function: #Function<4.39288908/0 in Scenic.Driver.Glfw.Graph.render_graphs/3>
    Args: []
```

Workaround is to depend on master branch of scenic_driver_glfw.

**Comment by boydm** [comment]
It is now published on hex

**Comment by axelson** [comment]
Thanks! :tada:
